name: Snake animation

on:
  schedule:
    - cron: '0 0 * * *'  # roda todo dia à meia-noite UTC
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install github-contribution-snake

      - name: Generate snake animation SVGs
        run: |
          mkdir -p output
          github-contribution-snake --user ${{ github.repository_owner }} --output output

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add output/snake.svg output/snake-dark.svg
          git commit -m "Update snake animation" || echo "No changes to commit"
          git push

