name: Snake animation

on:
  schedule:
    - cron: '0 0 * * *'  # roda todo dia à meia-noite UTC
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Generate snake animation
        run: |
          npm install --global contribution-snake
          contribution-snake --username ${{ github.repository_owner }} --output ./output

      - name: Commit and push SVG files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add output/snake.svg output/snake-dark.svg
          git commit -m "Update snake animation" || echo "No changes to commit"
          git push
