name: Snake animation

on:
  schedule:
    - cron: '0 0 * * *'  # todo dia à meia-noite UTC
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install matplotlib numpy

      - name: Clone github-contribution-snake
        run: |
          git clone https://github.com/DenverCoder1/github-contribution-snake.git snake-tool

      - name: Run snake generator
        run: |
          mkdir -p output
          python snake-tool/snake.py --user ${{ github.repository_owner }} --output output

      - name: Commit and push SVG
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add output/snake.svg output/snake-dark.svg
          git commit -m "Update snake animation" || echo "No changes to commit"
          git push

